
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weebygomypbntkfuzvsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZWJ5Z29teXBibnRrZnV6dnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTkzMzMsImV4cCI6MjA1OTU3NTMzM30.l8qhpT_rSv0pjC4GDINoRFlvzRUy4XcxIzk9QGPeAbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
